"""Read-only host profiles with fixed argv (no user-controlled tokens in argv)."""

from __future__ import annotations

from typing import Final

from services.readonly.constants import PING_LOOPBACK_IPV4

FIXED_ARGV: Final[dict[str, tuple[list[str], int]]] = {
    "host_hostname": (["hostname"], 15),
    "host_hostnamectl": (["hostnamectl"], 20),
    "host_uname_a": (["uname", "-a"], 15),
    "host_uptime_cmd": (["uptime"], 15),
    "host_whoami": (["whoami"], 15),
    "host_id": (["id"], 15),
    "host_date": (["date"], 15),
    "host_timedatectl": (["timedatectl", "status"], 25),
    "host_pwd": (["pwd"], 15),
    "host_last_n": (["last", "-n", "40"], 25),
    "host_lastlog": (["lastlog"], 45),
    "host_w": (["w"], 20),
    "host_who": (["who"], 15),
    "host_users": (["users"], 15),
    "host_top_bn1": (["top", "-b", "-n", "1"], 45),
    "host_free_h": (["free", "-h"], 15),
    "host_vmstat": (["vmstat", "1", "3"], 25),
    "host_iostat_sn": (["iostat", "-y", "1", "3"], 35),
    "host_mpstat_sn": (["mpstat", "1", "3"], 35),
    "host_lscpu": (["lscpu"], 25),
    "host_nproc": (["nproc"], 10),
    "host_cat_proc_cpuinfo": (["cat", "/proc/cpuinfo"], 20),
    "host_cat_proc_meminfo": (["cat", "/proc/meminfo"], 20),
    "host_ps_aux_cpu": (["ps", "aux", "--sort=-%cpu"], 30),
    "host_ps_aux_mem": (["ps", "aux", "--sort=-%mem"], 30),
    "host_pstree": (["pstree", "-p", "-a"], 25),
    "host_df_h": (["df", "-h"], 30),
    "host_lsblk": (["lsblk", "-o", "NAME,SIZE,FSTYPE,MOUNTPOINT,MODEL,SERIAL"], 30),
    "host_blkid": (["blkid"], 30),
    "host_mount": (["mount"], 25),
    "host_findmnt": (["findmnt"], 25),
    "host_cat_fstab": (["cat", "/etc/fstab"], 15),
    "host_fdisk_l": (["fdisk", "-l"], 60),
    "host_parted_l": (["parted", "-l"], 60),
    "host_smartctl_scan": (["smartctl", "--scan"], 30),
    "host_nvme_list": (["nvme", "list"], 25),
    "host_dmesg_T": (["dmesg", "-T"], 35),
    "host_ip_br_addr": (["ip", "-br", "addr"], 20),
    "host_ip_route": (["ip", "route"], 20),
    "host_ss_tulpn": (["ss", "-tulpn"], 25),
    "host_hostname_I": (["hostname", "-I"], 10),
    "host_sensors_a": (["sensors", "-A"], 30),
    "host_lsusb": (["lsusb"], 25),
    "host_lspci": (["lspci"], 25),
    "host_pidstat_sn": (["pidstat", "1", "2"], 30),
    "host_lsof_listeners": (["lsof", "-nP", "-iTCP", "-sTCP:LISTEN"], 35),
    "docker_cli_ps": (["docker", "ps"], 30),
    "docker_cli_ps_a": (["docker", "ps", "-a"], 45),
    "docker_cli_images": (["docker", "images"], 60),
    "docker_cli_volume_ls": (["docker", "volume", "ls"], 25),
    "docker_cli_network_ls": (["docker", "network", "ls"], 25),
    "docker_cli_stats": (["docker", "stats", "--no-stream"], 90),
    "docker_cli_system_df": (["docker", "system", "df"], 45),
    "docker_cli_info": (["docker", "info"], 60),
    "docker_cli_version": (["docker", "version"], 30),
    "docker_compose_ps": (["docker", "compose", "ps"], 45),
    "kubectl_get_pods": (["kubectl", "get", "pods", "-A", "-o", "wide", "--request-timeout=20s"], 45),
    "kubectl_get_nodes": (["kubectl", "get", "nodes", "-o", "wide", "--request-timeout=20s"], 35),
    "helm_list_a": (["helm", "list", "-A", "--max", "200"], 45),
    "service_status_all": (["service", "--status-all"], 60),
    "systemctl_list_units": (
        ["systemctl", "list-units", "--type=service", "--no-pager", "--no-legend"],
        45,
    ),
    "systemctl_list_timers": (["systemctl", "list-timers", "--all", "--no-pager"], 35),
    # Loopback only — see services.readonly.constants.PING_LOOPBACK_IPV4
    "host_ping": (["ping", "-c", "4", "-W", "5", PING_LOOPBACK_IPV4], 35),
}
